/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.koneksi.Koneksi;
import com.koneksi.Session;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author muham
 */
public class Laporan extends javax.swing.JFrame {

    /**
     * Creates new form Laporan
     */
    public Laporan() {
         
        conn = new Koneksi();
        initComponents();
        kasirTxt.setText(Session.getUsername() );
        tabel1();
        tabel();
    }

     
    Koneksi conn;
    ResultSet rs;
    DefaultTableModel data;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        kasirTxt = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        posBT = new javax.swing.JLabel();
        kasirBT = new javax.swing.JLabel();
        laporanBT = new javax.swing.JLabel();
        productBT3 = new javax.swing.JLabel();
        kasirTxt1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        categoryBT2 = new javax.swing.JLabel();
        categoryBT5 = new javax.swing.JLabel();
        categoryBT7 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        kasirTxt.setBackground(new java.awt.Color(255, 255, 255));
        kasirTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kasirTxt.setForeground(new java.awt.Color(255, 51, 255));
        kasirTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asset/20221217_204900_0000 (1) - Copy.png"))); // NOI18N
        kasirTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kasirTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasirTxtMouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 51, 255));
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        posBT.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        posBT.setForeground(new java.awt.Color(255, 51, 255));
        posBT.setText("POS");
        posBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        posBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posBTMouseClicked(evt);
            }
        });

        kasirBT.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kasirBT.setForeground(new java.awt.Color(255, 51, 255));
        kasirBT.setText("Kasir");
        kasirBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kasirBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasirBTMouseClicked(evt);
            }
        });

        laporanBT.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        laporanBT.setForeground(new java.awt.Color(255, 51, 255));
        laporanBT.setText("Laporan");
        laporanBT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanBTMouseClicked(evt);
            }
        });

        productBT3.setBackground(new java.awt.Color(255, 255, 255));
        productBT3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        productBT3.setForeground(new java.awt.Color(255, 51, 255));
        productBT3.setText("Produk");
        productBT3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productBT3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productBT3MouseClicked(evt);
            }
        });

        kasirTxt1.setBackground(new java.awt.Color(255, 255, 255));
        kasirTxt1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        kasirTxt1.setForeground(new java.awt.Color(255, 51, 255));
        kasirTxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kasirTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasirTxt1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laporanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kasirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posBT, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productBT3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(kasirTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(kasirTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(kasirTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(kasirTxt)))
                .addGap(91, 91, 91)
                .addComponent(productBT3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(posBT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(laporanBT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kasirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 255));
        jLabel16.setText("LAPORAN");

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Kasir", "Total Penjualan"
            }
        ));
        tabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabel1.setSelectionBackground(new java.awt.Color(153, 0, 153));
        tabel1.setShowGrid(true);
        tabel1.setShowHorizontalLines(false);
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel1);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Kasir", "Nama Barang", "Qty", "SubTotal", "Total"
            }
        ));
        tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabel.setSelectionBackground(new java.awt.Color(153, 0, 153));
        tabel.setShowGrid(true);
        tabel.setShowHorizontalLines(false);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel);

        categoryBT2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        categoryBT2.setForeground(new java.awt.Color(255, 51, 255));
        categoryBT2.setText("Penjualan Produk");
        categoryBT2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        categoryBT2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryBT2MouseClicked(evt);
            }
        });

        categoryBT5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        categoryBT5.setForeground(new java.awt.Color(255, 51, 255));
        categoryBT5.setText("Total Penjualan Kasir");
        categoryBT5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        categoryBT5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryBT5MouseClicked(evt);
            }
        });

        categoryBT7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        categoryBT7.setForeground(new java.awt.Color(255, 51, 255));
        categoryBT7.setText("Search");
        categoryBT7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        categoryBT7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryBT7MouseClicked(evt);
            }
        });

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(411, 411, 411)
                                .addComponent(jLabel16))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(categoryBT2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(categoryBT7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(categoryBT5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(212, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel16)
                .addGap(15, 15, 15)
                .addComponent(categoryBT5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryBT2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryBT7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void tabel1(){ 
        data = new DefaultTableModel (new String[] {
            "Tanggal",
            "Kasir",
            "Total Penjualan",
        },0);
        
        rs = conn.selectSl();
        try {
            while (rs.next() ) {
                data.addRow(new Object[] {
                    rs.getString("date"),
                    rs.getString("kasir"),
                    rs.getString("total" ),
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
         tabel1.setModel(data);
    }
    private void kasirTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasirTxtMouseClicked
        // TODO add your handling code here:
        Product p = new Product();
        this.hide();
        p.setVisible(true);
    }//GEN-LAST:event_kasirTxtMouseClicked

    public void tabel() { 
        data = new DefaultTableModel (new String[] { 
            "Tanggal",
            "Kasir", 
            "Nama Barang",
            "Qty",
            "Subtotal",
            "Total",
            
        }, 0);
        
        rs = conn.selectSlPr();
        try {
            while (rs.next() ) {
                
                data.addRow(new Object[] { 
                    rs.getString("date"),
                    rs.getString("kasir"),
                    rs.getString("nama"),
                    rs.getString("qty"),
                    rs.getString("subtotal"),
                    rs.getString("total"),
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.setModel(data);
    }
    private void posBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posBTMouseClicked
        // TODO add your handling code here:
        PointOfSales p = new PointOfSales();
        this.hide();
        p.setVisible(true);
    }//GEN-LAST:event_posBTMouseClicked

    private void kasirBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasirBTMouseClicked
        // TODO add your handling code here:
        Kasir k = new Kasir();
        this.hide();
        k.setVisible(true);
    }//GEN-LAST:event_kasirBTMouseClicked

    private void laporanBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanBTMouseClicked
        // TODO add your handling code here:
        Laporan l = new Laporan();
        this.hide();
        l.setVisible(true);
    }//GEN-LAST:event_laporanBTMouseClicked

    private void productBT3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBT3MouseClicked
        // TODO add your handling code here:
        Product p = new Product();
        this.hide();
        p.setVisible(true);
        
    }//GEN-LAST:event_productBT3MouseClicked

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel1MouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void categoryBT2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryBT2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryBT2MouseClicked

    private void categoryBT5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryBT5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryBT5MouseClicked

    private void kasirTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasirTxt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kasirTxt1MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        int dialog = JOptionPane.showConfirmDialog(null,"Yakin?","Keluar",JOptionPane.YES_NO_OPTION);
        if (dialog == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void categoryBT7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryBT7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryBT7MouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        String cari = search.getText();
        TableRowSorter sorter = new TableRowSorter(data);
        tabel.setRowSorter(sorter);
        
        sorter.setRowFilter(RowFilter.regexFilter(cari));
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                if ( Session.getCek() == null ) {
                    JOptionPane.showMessageDialog(null, "Kamu Belom Login");
                    new Laporan().setVisible(false);
                    new Login().setVisible(true);
                } else {
                    new Laporan().setVisible(true);
                }
                    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryBT2;
    private javax.swing.JLabel categoryBT5;
    private javax.swing.JLabel categoryBT7;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel kasirBT;
    private javax.swing.JLabel kasirTxt;
    private javax.swing.JLabel kasirTxt1;
    private javax.swing.JLabel laporanBT;
    private javax.swing.JLabel posBT;
    private javax.swing.JLabel productBT3;
    private javax.swing.JTextField search;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabel1;
    // End of variables declaration//GEN-END:variables
}
